//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom
    {
        public Classroom()
        {
            this.Courses = new HashSet<Cours>();
        }
    
        public int ClassroomID { get; set; }
        public string RoomNumber { get; set; }
        public short RoomSize { get; set; }
    
        public virtual ICollection<Cours> Courses { get; set; }
    }

//------------------------------------------------------------------------------
// <manually-generated>
//    This code was generated from fingertips and brainpower.
//
//    Manual changes to this file may cause required behavior in your application.
//    Manual changes to this file will disappear if the code is regenerated.
// </manually generated>
//------------------------------------------------------------------------------


    public partial class Classroom
    {
        databaseManager dm = new databaseManager();

        private List<CourseTime> timesUsed;

        public List<CourseTime> TimesUsed
        {
            get
            {
                return timesUsed;
            }
            private set
            {
                timesUsed = value;
            }
        }
        public void SetTimes()
        {
            this.TimesUsed = dm.DBTimes;
        }
    }
}
