//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom
    {
        public Classroom()
        {
            this.Courses = new HashSet<Cours>();
        }
    
        public int ClassroomID { get; set; }
        public string RoomNumber { get; set; }
        public short RoomSize { get; set; }
    
        public virtual ICollection<Cours> Courses { get; set; }
    }
}
